apiVersion: v1
kind: Pod
metadata:
  name: emptyDirApp
  labels:
    app: empty-dir
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
