apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
    resource:
      request:
        memory: "1Gi"
        cpu: 1
      limit:
        memory: "2Gi"
        cpu: 2
