apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
    type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      requests:
        memory: "1Gi"
        cpu: 1
      limits:
        memory: "2Gi"
        cpu: 2
  tolerations:
  - key: "my-app"
    operator: "Equal"
    value: "front-end"
    effect: "NoSchedule"
